services:
  # mineadmin的.env的mysql、redis如果连接到宿主机，地址用：host.docker.internal
  # 如果是连接到docker内服务，则用服务名称，如:redis
  hgyk-admin-api:
    build: .
    restart: always
    container_name: hgyk-admin-api
    working_dir: "/opt/www"
    ports:
      - 9501:9501
      - 9502:9502
      - 9503:9503
    volumes:
      - ./:/opt/www
